// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package rdbms

import (
	"context"
)

const getAllMetadata = `-- name: GetAllMetadata :many
SELECT product_id, platform_name, identifier FROM product_platform
`

func (q *Queries) GetAllMetadata(ctx context.Context) ([]ProductPlatform, error) {
	rows, err := q.db.QueryContext(ctx, getAllMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductPlatform
	for rows.Next() {
		var i ProductPlatform
		if err := rows.Scan(&i.ProductID, &i.PlatformName, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
